config/routes.rb
Rails.application.routes.draw do
  resources :scheduleds
  resources :scheduleds
  devise_for :users
  resources :sendeds
  resources :groups
  resources :contacts
  resources :events
  resources :commands
  resources :receiveds
  
  root 'receiveds#index'

end

app/models/command.rb
class Command < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_and_belongs_to_many :groups
	has_and_belongs_to_many :scheduleds
end

app/models/contacts_group.rb
class ContactsGroup < ActiveRecord::Base
end

app/models/contacts_scheduled.rb
class ContactsScheduled < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :contacts
	has_and_belongs_to_many :scheduleds
end

app/models/groups_scheduled.rb
class GroupsScheduled < ActiveRecord::Base
end

app/models/numbers_scheduled.rb
class NumbersScheduled < ActiveRecord::Base
end

app/models/received.rb
class Received < ActiveRecord::Base
end

app/models/scheduled.rb
class Scheduled < ActiveRecord::Base
	has_and_belongs_to_many :groups
	has_and_belongs_to_many :contacts
end

app/models/sended.rb
class Sended < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:type, :text)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    usersId = ContactsGroup.where(['group_id = :group_id', { group_id: params[:id] }])
    @users = []
    usersId.each do |id|
      @users << Contact.find_by_id(id.contact_id)
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
    @contacts = Contact.all
    @usersInGroup = []
  end

  # GET /groups/1/edit
  def edit
    @contacts = Contact.all
    usersId = ContactsGroup.where(['group_id = :group_id', { group_id: params[:id] }])
    @usersInGroup = []
    usersId.each do |id|
      @usersInGroup << Contact.find_by_id(id.contact_id)
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    users = params[:contacts]
    respond_to do |format|
      if @group.save
        if users
          users.each do |user|
            if !Contact.find_by_id(user).nil?
              ContactsGroup.create(group_id: @group.id, contact_id: user)
            end
          end
        end
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update    
    users = params[:contacts]
    respond_to do |format|
      if @group.update(group_params)
        ContactsGroup.destroy_all(group_id: params[:id])
        if users
          users.each do |user|
            if !Contact.find_by_id(user).nil?
              ContactsGroup.create(group_id: @group.id, contact_id: user)
            end
          end
        end
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/controllers/sendeds_controller.rb
class SendedsController < ApplicationController
  before_action :set_sended, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /sendeds
  # GET /sendeds.json
  def index
    @sendeds = Sended.all
  end

  # GET /sendeds/1
  # GET /sendeds/1.json
  def show
  end

  # GET /sendeds/new
  def new
    @sended = Sended.new
  end

  # GET /sendeds/1/edit
  def edit
  end

  # POST /sendeds
  # POST /sendeds.json
  def create
    @sended = Sended.new(sended_params)

    respond_to do |format|
      if @sended.save
        format.html { redirect_to @sended, notice: 'Sended was successfully created.' }
        format.json { render :show, status: :created, location: @sended }
      else
        format.html { render :new }
        format.json { render json: @sended.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sendeds/1
  # PATCH/PUT /sendeds/1.json
  def update
    respond_to do |format|
      if @sended.update(sended_params)
        format.html { redirect_to @sended, notice: 'Sended was successfully updated.' }
        format.json { render :show, status: :ok, location: @sended }
      else
        format.html { render :edit }
        format.json { render json: @sended.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sendeds/1
  # DELETE /sendeds/1.json
  def destroy
    @sended.destroy
    respond_to do |format|
      format.html { redirect_to sendeds_url, notice: 'Sended was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sended
      @sended = Sended.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sended_params
      params.require(:sended).permit(:target, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/receiveds_helper.rb
module ReceivedsHelper
end

app/helpers/scheduleds_helper.rb
module ScheduledsHelper
end

app/helpers/sendeds_helper.rb
module SendedsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="container-fluid">
  <% if notice %>
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Successfuly</h3>
    </div>
    <div class="panel-body">
      <%= notice %>
    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">All Events</h1>
    </div>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Type</th>
        <th>Text</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.id %></td>
          <td><%= event.type %></td>
          <td><%= event.text %></td>
          <td class="btn-position-table">
            <%= link_to edit_event_path(event), class: "btn btn-info" do %>
               <%= icon('edit', 'Edit') %>
            <% end %>
            
            <%= link_to event, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" do %>
              <%= icon('trash-o', 'Delete') %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New Event', new_event_path, class: "btn btn-success" %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @event.type %>
</p>

<p>
  <strong>Text:</strong>
  <%= @event.text %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form class="form-horizontal">
    <div class="form-group">
     <%= f.label :name, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %> <br>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2">Liste contact : </label><br>
      <div class="col-sm-10 ">
        <% @contacts.each do |contact| %>
          <div class="col-sm-4  ">
            <% if @usersInGroup.include? contact %>
              <%= check_box_tag "contacts[]", contact.id, true %>
            <% else %>
              <%= check_box_tag "contacts[]", contact.id, false %>
            <% end %>
            <%= label_tag(:contact, contact.name) %> 
            </div>
          <% end %>
      </div>    
    </div>
    <div class="clearfix"></div>
    <div class="form-group">
      <div class="col-sm-10">
        <% if action_name == "edit"%>
          <%= f.submit "Update group", class: "btn btn-success"  %>
        <% else %>
          <%= f.submit "Create group", class: "btn btn-success"  %>
        <% end %>
        <%= link_to 'Back', groups_path, class: "btn btn-danger" %>
      </div>
    </div>
  </form>
<% end %>

app/views/groups/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Edit Group</h1>
    </div>
  </div>
  <div class="container">
  	<%= render 'form' %>
  </div>
</div>

app/views/groups/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="container-fluid">
  <% if notice %>
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Successfuly</h3>
    </div>
    <div class="panel-body">
      <%= notice %>
    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">All Groups</h1>
    </div>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td><%= group.id %></td>
          <td><%= group.name %></td>
          <td class="btn-position-table">
            <%= link_to group, class: "btn btn-success" do %>
              <%= icon('eye', 'Show') %>
            <% end %>

            <%= link_to edit_group_path(group), class: "btn btn-info" do %>
               <%= icon('edit', 'Edit') %>
            <% end %>
            
            <%= link_to group, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" do %>
              <%= icon('trash-o', 'Delete') %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New Group', new_group_path, class: "btn btn-success" %>
</div>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div class="container-fluid">
	<% if notice %>
	  <div class="panel panel-success" id="infoBox">
	    <div class="panel-heading">
	      <h3 class="panel-title">Successfuly</h3>
	    </div>
	    <div class="panel-body">
	      <%= notice %>
	    </div>
	  </div>
	<% end %>

	<div class="row">
	    <div class="col-lg-12">
	      <h1 class="page-header">Group : <%= @group.name %></h1>
	    </div>
	</div>
	<table class="table table-striped table-hover">
		<thead>
		  <tr>
		    <th>#</th>
		    <th>Name</th>
		    <th>Number</th>
		  </tr>
		</thead>
		<tbody>
		    <% @users.each do |contact| %>
		    	<tr>
		    		<td><%= contact.id %></td>
		    		<td><%= contact.name %></td>
		    		<td><%= contact.number %></td>
		    	</tr>
			<% end %>
		</tbody>
	</table>	
	<%= link_to 'Edit', edit_group_path(@group), class: "btn btn-success" %>
	<%= link_to 'Back', groups_path, class: "btn btn-danger" %>
 </div>


<script type="text/javascript">
  jQuery(document).ready(function() {
    infoBoxFadeOut();
  })

</script>

app/views/sendeds/_form.html.erb
<%= form_for(@sended) do |f| %>
  <% if @sended.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sended.errors.count, "error") %> prohibited this sended from being saved:</h2>

      <ul>
      <% @sended.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :target %><br>
    <%= f.text_field :target %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sendeds/edit.html.erb
<h1>Editing Sended</h1>

<%= render 'form' %>

<%= link_to 'Show', @sended %> |
<%= link_to 'Back', sendeds_path %>

app/views/sendeds/index.html.erb
<div class="container-fluid">
  <% if notice %>
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Successfuly</h3>
    </div>
    <div class="panel-body">
      <%= notice %>
    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">All Sendeds</h1>
    </div>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Envoyé à</th>
        <th>Texte</th>
        <th colspan="3"></th>
      </tr>
    </thead>
     <tbody>
        <% @sendeds.each do |sended| %>
          <tr>
            <td><%= sended.target %></td>
            <td><%= sended.content %></td>
            <td class="btn-position-table">
             <%= link_to sended, class: "btn btn-success" do %>
              <%= icon('eye', 'Show') %>
            <% end %>
              <%= link_to sended, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" do %>
              <%= icon('trash-o', 'Delete') %>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
  </table>
  <%= link_to 'New scheduled', new_scheduled_path, class: "btn btn-success"  %>
</div>

app/views/sendeds/new.html.erb
<h1>New Sended</h1>

<%= render 'form' %>

<%= link_to 'Back', sendeds_path %>

app/views/sendeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Target:</strong>
  <%= @sended.target %>
</p>

<p>
  <strong>Content:</strong>
  <%= @sended.content %>
</p>

<%= link_to 'Edit', edit_sended_path(@sended) %> |
<%= link_to 'Back', sendeds_path %>