config/routes.rb
Rails.application.routes.draw do
  resources :scheduleds
  resources :scheduleds
  devise_for :users
  resources :sendeds
  resources :groups
  resources :contacts
  resources :events
  resources :commands
  resources :receiveds
  
  root 'receiveds#index'

end

app/models/command.rb
class Command < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_and_belongs_to_many :groups
	has_and_belongs_to_many :scheduleds
end

app/models/contacts_group.rb
class ContactsGroup < ActiveRecord::Base
end

app/models/contacts_scheduled.rb
class ContactsScheduled < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :contacts
	has_and_belongs_to_many :scheduleds
end

app/models/groups_scheduled.rb
class GroupsScheduled < ActiveRecord::Base
end

app/models/numbers_scheduled.rb
class NumbersScheduled < ActiveRecord::Base
end

app/models/received.rb
class Received < ActiveRecord::Base
end

app/models/scheduled.rb
class Scheduled < ActiveRecord::Base
	has_and_belongs_to_many :groups
	has_and_belongs_to_many :contacts
end

app/models/sended.rb
class Sended < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:type, :text)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    usersId = ContactsGroup.where(['group_id = :group_id', { group_id: params[:id] }])
    @users = []
    usersId.each do |id|
      @users << Contact.find_by_id(id.contact_id)
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
    @contacts = Contact.all
    @usersInGroup = []
  end

  # GET /groups/1/edit
  def edit
    @contacts = Contact.all
    usersId = ContactsGroup.where(['group_id = :group_id', { group_id: params[:id] }])
    @usersInGroup = []
    usersId.each do |id|
      @usersInGroup << Contact.find_by_id(id.contact_id)
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    users = params[:contacts]
    respond_to do |format|
      if @group.save
        if users
          users.each do |user|
            if !Contact.find_by_id(user).nil?
              ContactsGroup.create(group_id: @group.id, contact_id: user)
            end
          end
        end
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update    
    users = params[:contacts]
    respond_to do |format|
      if @group.update(group_params)
        ContactsGroup.destroy_all(group_id: params[:id])
        if users
          users.each do |user|
            if !Contact.find_by_id(user).nil?
              ContactsGroup.create(group_id: @group.id, contact_id: user)
            end
          end
        end
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/controllers/receiveds_controller.rb
class ReceivedsController < ApplicationController
  before_action :set_received, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /receiveds
  # GET /receiveds.json
  def index
    @receiveds = Received.all
  end

  # GET /receiveds/1
  # GET /receiveds/1.json
  def show
  end

  # GET /receiveds/new
  def new
    @received = Received.new
  end

  # GET /receiveds/1/edit
  def edit
  end

  # POST /receiveds
  # POST /receiveds.json
  def create
    @received = Received.new(received_params)

    respond_to do |format|
      if @received.save
        format.html { redirect_to @received, notice: 'Received was successfully created.' }
        format.json { render :show, status: :created, location: @received }
      else
        format.html { render :new }
        format.json { render json: @received.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receiveds/1
  # PATCH/PUT /receiveds/1.json
  def update
    respond_to do |format|
      if @received.update(received_params)
        format.html { redirect_to @received, notice: 'Received was successfully updated.' }
        format.json { render :show, status: :ok, location: @received }
      else
        format.html { render :edit }
        format.json { render json: @received.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receiveds/1
  # DELETE /receiveds/1.json
  def destroy
    @received.destroy
    respond_to do |format|
      format.html { redirect_to receiveds_url, notice: 'Received was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_received
      @received = Received.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def received_params
      params.require(:received).permit(:send_by, :content, :is_command)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/receiveds_helper.rb
module ReceivedsHelper
end

app/helpers/scheduleds_helper.rb
module ScheduledsHelper
end

app/helpers/sendeds_helper.rb
module SendedsHelper
end

app/views/receiveds/_form.html.erb
<%= form_for(@received) do |f| %>
  <% if @received.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@received.errors.count, "error") %> prohibited this received from being saved:</h2>

      <ul>
      <% @received.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :send_by %><br>
    <%= f.text_field :send_by %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :is_command %><br>
    <%= f.check_box :is_command %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receiveds/edit.html.erb
<h1>Editing Received</h1>

<%= render 'form' %>

<%= link_to 'Show', @received %> |
<%= link_to 'Back', receiveds_path %>

app/views/receiveds/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="container-fluid">
  <% if notice %>
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Successfuly</h3>
    </div>
    <div class="panel-body">
      <%= notice %>
    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">All Receiveds</h1>
    </div>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Send by</th>
        <th>Text</th>
        <th>Command</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @receiveds.each do |received| %>
        <tr>
          <td><%= received.id %></td>
          <td><%= received.send_by %></td>
          <td><%= received.content %></td>
          <td><%= received.is_command %></td>
          <td class="btn-position-table">
            <%= link_to edit_received_path(received), class: "btn btn-info" do %>
               <%= icon('edit', 'Edit') %>
            <% end %>
            
            <%= link_to received, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" do %>
              <%= icon('trash-o', 'Delete') %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/receiveds/new.html.erb
<h1>New Received</h1>

<%= render 'form' %>

<%= link_to 'Back', receiveds_path %>

app/views/receiveds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Send by:</strong>
  <%= @received.send_by %>
</p>

<p>
  <strong>Content:</strong>
  <%= @received.content %>
</p>

<p>
  <strong>Is command:</strong>
  <%= @received.is_command %>
</p>

<%= link_to 'Edit', edit_received_path(@received) %> |
<%= link_to 'Back', receiveds_path %>