config/routes.rb
Rails.application.routes.draw do
  resources :scheduleds
  resources :scheduleds
  devise_for :users
  resources :sendeds
  resources :groups
  resources :contacts
  resources :events
  resources :commands
  resources :receiveds
  
  root 'receiveds#index'

end

app/models/scheduled.rb
class Scheduled < ActiveRecord::Base
	has_and_belongs_to_many :groups
	has_and_belongs_to_many :contacts
end

app/controllers/scheduleds_controller.rb
class ScheduledsController < ApplicationController
  before_action :set_scheduled, only: [:show, :edit, :update, :destroy]

  # GET /scheduleds
  # GET /scheduleds.json
  def index
    @scheduleds = Scheduled.all
  end

  # GET /scheduleds/1
  # GET /scheduleds/1.json
  def show
  end

  # GET /scheduleds/new
  def new
    @scheduled = Scheduled.new
    @contacts = Contact.all
    @groups = Group.all

    @contactsInGroup = []
    @groupsInGroup = []
  end

  # GET /scheduleds/1/edit
  def edit
    @contacts = Contact.all
    @groups = Group.all

    contactsId = ContactsScheduled.where(['scheduled_id = :scheduled_id', { scheduled_id: params[:id] }])
    @contactsInGroup = []
    contactsId.each do |id|
      @contactsInGroup << Contact.find_by_id(id.contact_id)
    end

    groupsId = GroupsScheduled.where(['scheduled_id = :scheduled_id', { scheduled_id: params[:id] }])
    @groupsInGroup = []
    groupsId.each do |id|
      @groupsInGroup << Group.find_by_id(id.group_id)
    end
  end

  # POST /scheduleds
  # POST /scheduleds.json
  def create
    @scheduled = Scheduled.new(scheduled_params)

    if params[:contacts]
      dest_contacts = params[:contacts]
    end

    if params[:groups]
      dest_groups = params[:groups]
    end

    respond_to do |format|
      if @scheduled.save
        
        if dest_contacts
          dest_contacts.each do |dest_contact|
            if !Contact.find_by_id(dest_contact).nil?
             ContactsScheduled.create(scheduled_id: @scheduled.id, contact_id: dest_contact)
            end
          end
        end

        if dest_groups
          dest_groups.each do |dest_group|
            if !Group.find_by_id(dest_group).nil?
             GroupsScheduled.create(scheduled_id: @scheduled.id, group_id: dest_group)
            end
          end
        end
            
         
        format.html { redirect_to @scheduled, notice: 'Scheduled was successfully created.' }
        format.json { render :show, status: :created, location: @scheduled }
      else
        format.html { render :new }
        format.json { render json: @scheduled.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scheduleds/1
  # PATCH/PUT /scheduleds/1.json
  def update

    if params[:contacts]
      dest_contacts = params[:contacts]
    end

    if params[:groups]
      dest_groups = params[:groups]
    end
    respond_to do |format|
      if @scheduled.update(scheduled_params)

        ContactsScheduled.destroy_all(scheduled_id: params[:id])
        if dest_contacts
          dest_contacts.each do |dest_contact|
            if !Contact.find_by_id(dest_contact).nil?
              ContactsScheduled.create(scheduled_id: @scheduled.id, contact_id: dest_contact)
            end
          end
        end

        GroupsScheduled.destroy_all(scheduled_id: params[:id])
        if dest_groups
          dest_groups.each do |dest_group|
            if !Group.find_by_id(dest_group).nil?
              GroupsScheduled.create(scheduled_id: @scheduled.id, group_id: dest_group)
            end
          end
        end

        format.html { redirect_to @scheduled, notice: 'Scheduled was successfully updated.' }
        format.json { render :show, status: :ok, location: @scheduled }
      else
        format.html { render :edit }
        format.json { render json: @scheduled.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scheduleds/1
  # DELETE /scheduleds/1.json
  def destroy
    @scheduled.destroy
    respond_to do |format|
      format.html { redirect_to scheduleds_url, notice: 'Scheduled was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheduled
      @scheduled = Scheduled.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scheduled_params

      params.require(:scheduled).permit(:content, :progress, :send_at)

    end
end

app/helpers/scheduleds_helper.rb
module ScheduledsHelper
end

app/views/scheduleds/_form.html.erb
<%= simple_form_for @scheduled do |f| %>
  <% if @scheduled.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scheduled.errors.count, "error") %> prohibited this scheduled from being saved:</h2>

      <ul>
      <% @scheduled.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-inputs">
    <%= f.input :content %>

    <%= f.input :send_at, class: "input-group date", id: "datetimepicker2" %>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker2').datetimepicker();
            });
        </script>

  

    <label>Numéro ciblé</label><br>
    

    
    <label>Contacts cibles </label><br>
    <% @contacts.each do |contact| %>
      <% if @contactsInGroup.include? contact %>
        <%= check_box_tag "contacts[]", contact.id, true %>
      <% else %>
        <%= check_box_tag "contacts[]", contact.id, false %>
      <% end %>
      <%= label_tag(:contact, contact.name) %>
    <% end %>
    <br>
     <label>Groups cibles </label><br>
     <% @groups.each do |group| %>
      <% if @groupsInGroup.include? group %>
        <%= check_box_tag "groups[]", group.id, true %>
      <% else %>
        <%= check_box_tag "groups[]", group.id, false %>
      <% end %>
      <%= label_tag(:group, group.name) %>
    <% end %>
    <br>

    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/scheduleds/edit.html.erb
<h1>Editing Scheduled</h1>

<%= render 'form' %>

<%= link_to 'Show', @scheduled %> |
<%= link_to 'Back', scheduleds_path %>

app/views/scheduleds/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="container-fluid">
  <% if notice %>
  <div class="panel panel-success" id="infoBox">
    <div class="panel-heading">
      <h3 class="panel-title">Successfuly</h3>
    </div>
    <div class="panel-body">
      <%= notice %>
    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">All Scheduleds</h1>
    </div>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Content</th>
        <th>Send at</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @scheduleds.each do |scheduled| %>
        <tr>
          <td><%= scheduled.id %></td>
          <td><%= scheduled.content %></td>
          <td><%= scheduled.send_at %></td>
          <td class="btn-position-table">
             <%= link_to scheduled, class: "btn btn-success" do %>
              <%= icon('eye', 'Show') %>
            <% end %>
            <%= link_to edit_scheduled_path(scheduled), class: "btn btn-info" do %>
               <%= icon('edit', 'Edit') %>
            <% end %>
            
            <%= link_to scheduled, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" do %>
              <%= icon('trash-o', 'Delete') %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New scheduled', new_scheduled_path, class: "btn btn-success" %>
</div>

<script type="text/javascript">
  jQuery(document).ready(function() {
    infoBoxFadeOut();
  })

</script>

app/views/scheduleds/new.html.erb
<h1>New Scheduled</h1>

<%= render 'form' %>

<%= link_to 'Back', scheduleds_path %>

app/views/scheduleds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @scheduled.content %>
</p>

<p>
  <strong>Progress:</strong>
  <%= @scheduled.progress %>
</p>

<p>
  <strong>Send at:</strong>
  <%= @scheduled.send_at %>
</p>

<%= link_to 'Edit', edit_scheduled_path(@scheduled) %> |
<%= link_to 'Back', scheduleds_path %>