config/routes.rb
Rails.application.routes.draw do
  resources :scheduleds
  resources :scheduleds
  devise_for :users
  resources :sendeds
  resources :groups
  resources :contacts
  resources :events
  resources :commands
  resources :receiveds
  
  root 'receiveds#index'

end

app/models/command.rb
class Command < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_and_belongs_to_many :groups
	has_and_belongs_to_many :scheduleds
end

app/models/contacts_group.rb
class ContactsGroup < ActiveRecord::Base
end

app/models/contacts_scheduled.rb
class ContactsScheduled < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :contacts
	has_and_belongs_to_many :scheduleds
end

app/models/groups_scheduled.rb
class GroupsScheduled < ActiveRecord::Base
end

app/models/numbers_scheduled.rb
class NumbersScheduled < ActiveRecord::Base
end

app/models/received.rb
class Received < ActiveRecord::Base
end

app/models/scheduled.rb
class Scheduled < ActiveRecord::Base
	has_and_belongs_to_many :groups
	has_and_belongs_to_many :contacts
end

app/models/sended.rb
class Sended < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_action :set_command, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /commands
  # GET /commands.json
  def index
    @commands = Command.all
  end

  # GET /commands/1
  # GET /commands/1.json
  def show
  end

  # GET /commands/new
  def new
    @command = Command.new
  end

  # GET /commands/1/edit
  def edit
  end

  # POST /commands
  # POST /commands.json
  def create
    @command = Command.new(command_params)

    respond_to do |format|
      if @command.save
        format.html { redirect_to @command, notice: 'Command was successfully created.' }
        format.json { render :show, status: :created, location: @command }
      else
        format.html { render :new }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commands/1
  # PATCH/PUT /commands/1.json
  def update
    respond_to do |format|
      if @command.update(command_params)
        format.html { redirect_to @command, notice: 'Command was successfully updated.' }
        format.json { render :show, status: :ok, location: @command }
      else
        format.html { render :edit }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commands/1
  # DELETE /commands/1.json
  def destroy
    @command.destroy
    respond_to do |format|
      format.html { redirect_to commands_url, notice: 'Command was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_command
      @command = Command.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def command_params
      params.require(:command).permit(:name, :script, :admin)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:type, :text)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    usersId = ContactsGroup.where(['group_id = :group_id', { group_id: params[:id] }])
    @users = []
    usersId.each do |id|
      @users << Contact.find_by_id(id.contact_id)
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
    @contacts = Contact.all
    @usersInGroup = []
  end

  # GET /groups/1/edit
  def edit
    @contacts = Contact.all
    usersId = ContactsGroup.where(['group_id = :group_id', { group_id: params[:id] }])
    @usersInGroup = []
    usersId.each do |id|
      @usersInGroup << Contact.find_by_id(id.contact_id)
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    users = params[:contacts]
    respond_to do |format|
      if @group.save
        if users
          users.each do |user|
            if !Contact.find_by_id(user).nil?
              ContactsGroup.create(group_id: @group.id, contact_id: user)
            end
          end
        end
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update    
    users = params[:contacts]
    respond_to do |format|
      if @group.update(group_params)
        ContactsGroup.destroy_all(group_id: params[:id])
        if users
          users.each do |user|
            if !Contact.find_by_id(user).nil?
              ContactsGroup.create(group_id: @group.id, contact_id: user)
            end
          end
        end
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/receiveds_helper.rb
module ReceivedsHelper
end

app/helpers/scheduleds_helper.rb
module ScheduledsHelper
end

app/helpers/sendeds_helper.rb
module SendedsHelper
end

app/views/commands/_form.html.erb
<%= form_for(@command) do |f| %>
  <% if @command.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@command.errors.count, "error") %> prohibited this command from being saved:</h2>

      <ul>
      <% @command.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :script %><br>
    <%= f.text_field :script %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commands/edit.html.erb
<h1>Editing Command</h1>

<%= render 'form' %>

<%= link_to 'Show', @command %> |
<%= link_to 'Back', commands_path %>

app/views/commands/index.html.erb
<div class="container-fluid">
  <% if notice %>
  <div class="panel panel-success" id="infoBox">
    <div class="panel-heading">
      <h3 class="panel-title">Successfuly</h3>
    </div>
    <div class="panel-body">
      <%= notice %>
    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Listing Commands</h1>
    </div>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Script</th>
        <th colspan="3"></th>
    </tr>
  </thead>
      </tr>
    </thead>

    <tbody>
      <% @commands.each do |command| %>
      <tr>
        <td><%= command.name %></td>
        <td><%= command.script %></td>
        <td class="btn-position-table">
          <%= link_to command, class: "btn btn-success" do %>
              <%= icon('eye', 'Show') %>
            <% end %>
          <%= link_to edit_command_path(command) , class: "btn btn-info" do %>
               <%= icon('edit', 'Edit') %>
          <% end %>
          <%= link_to command, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" do %>
              <%= icon('trash-o', 'Delete') %>
            <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New Command', new_command_path, class: "btn btn-success" %>
</div>

<script type="text/javascript">
  jQuery(document).ready(function() {
    infoBoxFadeOut();
  })

</script>

app/views/commands/new.html.erb
<h1>New Command</h1>

<%= render 'form' %>

<%= link_to 'Back', commands_path %>

app/views/commands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @command.name %>
</p>

<p>
  <strong>Script:</strong>
  <%= @command.script %>
</p>

<%= link_to 'Edit', edit_command_path(@command) %> |
<%= link_to 'Back', commands_path %>